# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "bsides" do |bsides|
    bsides.vm.box = "bsides"
    config.vm.network "forwarded_port", guest: 1234, host: 1234
    config.vm.network "forwarded_port", guest: 12345, host: 12345
    config.vm.box_check_update = false
    config.vm.synced_folder "shared-folder", "/remote"
  end

end
